[package]
name = "gitcask-wal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gitcask-proto.workspace = true
gitcask-store.workspace = true
gitcask-config.workspace = true
gitcask-git.workspace = true
anyhow.workspace = true
thiserror.workspace = true
bytes.workspace = true
futures.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
metrics.workspace = true
libc.workspace = true
parking_lot.workspace = true
dashmap.workspace = true
uuid.workspace = true
hex.workspace = true
tempfile.workspace = true
prost.workspace = true
prost-types.workspace = true
gix-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
utoipa.workspace = true
chrono.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["full", "test-util"] }
gitcask-store = { workspace = true, features = ["testing"] }

[lints]
workspace = true
